### PR TITLE
Issue #2 - Metrographic cut off

### PR DESCRIPTION
**Pull request by eriknewland**
Slightly shrank image to better fit the svg graphic template. If this is insufficient, I will try converting the image into an SVG (currently PNG, original was JPG) so it can scale better with the price-tracking graphic. 

Better centered the graphic/table contents.

### CODE REVIEW

**Comment by bitkarrot** [comment]
Thanks for the image resize, however

the original setup was a usd bill here: https://usdsat.com/
the HKD is pegged to the USD at a range bound 7.75 -7.85 HKD == 1 USD.

the USD Y axis has 9 ticks (1, 10, 100....etc), the HKD only has 6, this was the issue that i now recall needs fixing.

**Comment by bitkarrot** [comment]
Nice update! 

just one small adjustment, the Y axis gets cut off on smaller screens, any way to move it in a just a bit? 

Screenshot 2023-05-07 at 11 25 06 PM

Screenshot 2023-05-07 at 11 27 34 PM

**Comment by eriknewland** [comment]
I will take a look shortly and will either reduce the width for devices below 768px width (i think thats the general mobile threshold) or just adjust the width for all devices. I should have double checked layout across all devices!

**Comment by bitkarrot** [comment]
@eriknewland Beautiful! LFG!!

**Pull request merged**
